2020-10-06 14:27:25,289 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,289 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,289 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,290 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,290 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,290 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,291 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,291 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,291 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,293 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,293 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,293 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,294 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,294 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,294 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,295 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,295 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,295 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,297 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,297 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,297 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,298 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,298 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,298 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,299 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,299 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,299 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,301 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,301 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,301 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,302 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,302 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,302 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,303 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,303 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,303 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,306 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,306 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,306 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,307 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,307 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,307 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,308 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,308 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,308 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,309 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,309 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:25,309 - 33952 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 17, in __init__\n    temp = sys.argv[1]\n', 'IndexError: list index out of range\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\insertion.py", line 49, in record_insertion\n    query = "INSERT INTO " + table_name + " VALUES " + "(" + row + ")"\n', 'TypeError: can only concatenate str (not "list") to str\n']
2020-10-06 14:27:42,612 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,612 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,612 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,618 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,618 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,618 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,622 - 28584 INFO - status Records Inserted
2020-10-06 14:27:42,622 - 28584 INFO - status Records Inserted
2020-10-06 14:27:42,622 - 28584 INFO - status Records Inserted
2020-10-06 14:27:42,625 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,625 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,625 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,630 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,630 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,630 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,635 - 28584 INFO - address Records Inserted
2020-10-06 14:27:42,635 - 28584 INFO - address Records Inserted
2020-10-06 14:27:42,635 - 28584 INFO - address Records Inserted
2020-10-06 14:27:42,639 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,639 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,639 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,642 - 28584 INFO - stock Records Inserted
2020-10-06 14:27:42,642 - 28584 INFO - stock Records Inserted
2020-10-06 14:27:42,642 - 28584 INFO - stock Records Inserted
2020-10-06 14:27:42,646 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,646 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,646 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,652 - 28584 INFO - product Records Inserted
2020-10-06 14:27:42,652 - 28584 INFO - product Records Inserted
2020-10-06 14:27:42,652 - 28584 INFO - product Records Inserted
2020-10-06 14:27:42,657 - 28584 INFO - product Records Inserted
2020-10-06 14:27:42,657 - 28584 INFO - product Records Inserted
2020-10-06 14:27:42,657 - 28584 INFO - product Records Inserted
2020-10-06 14:27:42,661 - 28584 INFO - rating Records Inserted
2020-10-06 14:27:42,661 - 28584 INFO - rating Records Inserted
2020-10-06 14:27:42,661 - 28584 INFO - rating Records Inserted
2020-10-06 14:27:42,670 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,670 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,670 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,675 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,675 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,675 - 28584 INFO - details Records Inserted
2020-10-06 14:27:42,683 - 28584 INFO - ordered Records Inserted
2020-10-06 14:27:42,683 - 28584 INFO - ordered Records Inserted
2020-10-06 14:27:42,683 - 28584 INFO - ordered Records Inserted
2020-10-06 14:27:42,691 - 28584 INFO - status Records Inserted
2020-10-06 14:27:42,691 - 28584 INFO - status Records Inserted
2020-10-06 14:27:42,691 - 28584 INFO - status Records Inserted
2020-10-06 14:27:56,615 - 12964 INFO - category_details Records Inserted
2020-10-06 14:27:56,615 - 12964 INFO - category_details Records Inserted
2020-10-06 14:27:56,615 - 12964 INFO - category_details Records Inserted
2020-10-06 14:27:56,734 - 12964 INFO - customer_details Records Inserted
2020-10-06 14:27:56,734 - 12964 INFO - customer_details Records Inserted
2020-10-06 14:27:56,734 - 12964 INFO - customer_details Records Inserted
2020-10-06 14:27:56,874 - 12964 INFO - order_status_details Records Inserted
2020-10-06 14:27:56,874 - 12964 INFO - order_status_details Records Inserted
2020-10-06 14:27:56,874 - 12964 INFO - order_status_details Records Inserted
2020-10-06 14:27:57,050 - 12964 INFO - seller_details Records Inserted
2020-10-06 14:27:57,050 - 12964 INFO - seller_details Records Inserted
2020-10-06 14:27:57,050 - 12964 INFO - seller_details Records Inserted
2020-10-06 14:27:57,055 - 12964 INFO - cart_details Records Inserted
2020-10-06 14:27:57,055 - 12964 INFO - cart_details Records Inserted
2020-10-06 14:27:57,055 - 12964 INFO - cart_details Records Inserted
2020-10-06 14:27:57,143 - 12964 INFO - customer_address_details Records Inserted
2020-10-06 14:27:57,143 - 12964 INFO - customer_address_details Records Inserted
2020-10-06 14:27:57,143 - 12964 INFO - customer_address_details Records Inserted
2020-10-06 14:27:57,252 - 12964 INFO - order_details Records Inserted
2020-10-06 14:27:57,252 - 12964 INFO - order_details Records Inserted
2020-10-06 14:27:57,252 - 12964 INFO - order_details Records Inserted
2020-10-06 14:27:57,360 - 12964 INFO - product_stock_details Records Inserted
2020-10-06 14:27:57,360 - 12964 INFO - product_stock_details Records Inserted
2020-10-06 14:27:57,360 - 12964 INFO - product_stock_details Records Inserted
2020-10-06 14:27:57,475 - 12964 INFO - product_details Records Inserted
2020-10-06 14:27:57,475 - 12964 INFO - product_details Records Inserted
2020-10-06 14:27:57,475 - 12964 INFO - product_details Records Inserted
2020-10-06 14:27:57,595 - 12964 INFO - cart_product_details Records Inserted
2020-10-06 14:27:57,595 - 12964 INFO - cart_product_details Records Inserted
2020-10-06 14:27:57,595 - 12964 INFO - cart_product_details Records Inserted
2020-10-06 14:27:57,727 - 12964 INFO - category_product_details Records Inserted
2020-10-06 14:27:57,727 - 12964 INFO - category_product_details Records Inserted
2020-10-06 14:27:57,727 - 12964 INFO - category_product_details Records Inserted
2020-10-06 14:27:57,843 - 12964 INFO - customer_rating_details Records Inserted
2020-10-06 14:27:57,843 - 12964 INFO - customer_rating_details Records Inserted
2020-10-06 14:27:57,843 - 12964 INFO - customer_rating_details Records Inserted
2020-10-06 14:27:57,952 - 12964 INFO - invoice_details Records Inserted
2020-10-06 14:27:57,952 - 12964 INFO - invoice_details Records Inserted
2020-10-06 14:27:57,952 - 12964 INFO - invoice_details Records Inserted
2020-10-06 14:27:58,151 - 12964 INFO - payment_details Records Inserted
2020-10-06 14:27:58,151 - 12964 INFO - payment_details Records Inserted
2020-10-06 14:27:58,151 - 12964 INFO - payment_details Records Inserted
2020-10-06 14:27:58,257 - 12964 INFO - product_ordered_details Records Inserted
2020-10-06 14:27:58,257 - 12964 INFO - product_ordered_details Records Inserted
2020-10-06 14:27:58,257 - 12964 INFO - product_ordered_details Records Inserted
2020-10-06 14:27:58,367 - 12964 INFO - shipping_status Records Inserted
2020-10-06 14:27:58,367 - 12964 INFO - shipping_status Records Inserted
2020-10-06 14:27:58,367 - 12964 INFO - shipping_status Records Inserted
